import type { ComponentToken as AppComponentToken } from '../../app/style';
import type { ComponentToken as AlertComponentToken } from '../../alert/style';
import type { ComponentToken as LinkComponentToken } from '../../link/style';
import type { ComponentToken as ButtonComponentToken } from '../../button/style';
import type { ComponentToken as BacktopComponentToken } from '../../backtop/style';
import type { ComponentToken as CopyComponentToken } from '../../copy/style';
import type { ComponentToken as DividerComponentToken } from '../../divider/style';
import type { ComponentToken as DrawerComponentToken } from '../../drawer/style';
import type { ComponentToken as MessageComponentToken } from '../../message/style';
import type { ComponentToken as NotificationComponentToken } from '../../notification/style';
import type { ComponentToken as ModalComponentToken } from '../../modal/style';
import type { ComponentToken as IconComponentToken } from '../../icon/style';
import type { ComponentToken as DocumentComponentToken } from '../../document/style';
import type { ComponentToken as SpaceComponentToken } from '../../space/style';
import type { ComponentToken as SpinComponentToken } from '../../spin/style';
import type { ComponentToken as ImageComponentToken } from '../../image/style';
import type { ComponentToken as GeoJSONComponentToken } from '../../geojson/style';
import type { ComponentToken as WatermarkComponentToken } from '../../watermark/style';
import type { ComponentToken as GridComponentToken } from '../../grid/style';
import type { ComponentToken as EmptyComponentToken } from '../../empty/style';

export interface ComponentTokenMap {
  App?: AppComponentToken;
  Alert?: AlertComponentToken;
  Backtop?: BacktopComponentToken;
  Button?: ButtonComponentToken;
  Copy?: CopyComponentToken;
  Link?: LinkComponentToken;
  Drawer?: DrawerComponentToken;
  Divider?: DividerComponentToken;
  Message?: MessageComponentToken;
  Notification?: NotificationComponentToken;
  Modal?: ModalComponentToken;
  Icon?: IconComponentToken;
  Document?: DocumentComponentToken;
  Spin?: SpinComponentToken;
  Space?: SpaceComponentToken;
  Image?: ImageComponentToken;
  GeoJSON?: GeoJSONComponentToken;
  Watermark?: WatermarkComponentToken;
  Grid?: GridComponentToken;
  Empty?: EmptyComponentToken;
}
